### ISSUE TITLE
tdclient.errors.APIError: 400 {"error":"missing parameter ...

### ISSUE THREAD

**Issue by kimujinyogi** [treasure-data/td-client-python#34]
Hello

I have problems that I can not run sample code.

here my test code
```
import tdclient
apikey = 'xxxxxxx'
with tdclient.Client(apikey, endpoint='in.ybi.idcfcloud.net') as client:
    for db in client.databases():
        print db
```

and here error message.
```
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    for db in client.databases():
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/tdclient/client.py", line 81, in databases
    databases = self.api.list_databases()
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/tdclient/database_api.py", line 24, in list_databases
    self.raise_error("List databases failed", res, body)
  File "/opt/rh/python27/root/usr/lib/python2.7/site-packages/tdclient/api.py", line 373, in raise_error
    raise errors.APIError("%d: %s: %s" % (status_code, msg, s))
tdclient.errors.APIError: 400: List databases failed: {"error":"missing parameter: json=nil, write_apikey=nil, device=\"\", version=\"v3\", category=\"database\""}
```

How can I solve this problem?

**Comment by yyuu** [comment]
The `in.ybi.idcfcloud.net` is [the import endpoint for JavaScript/iOS/Android SDK](https://docs.treasuredata.com/articles/rest-api-import) (of [Traesure Data Service by IDCF](https://www.idcf.jp/bigdata/)) and unfortunately it doesn't provide full set of Treasure Data API. To use this Python SDK, you need to use https://api.in.ybi.idcfcloud.net/ in favor of https://in.ybi.idcfcloud.net/. Please try again later.

```python
import tdclient
apikey = 'xxxxxxx'
with tdclient.Client(apikey, endpoint='api.ybi.idcfcloud.net') as client:
    for db in client.databases():
        print db
```

**Comment by kimujinyogi** [comment]
Thank you. This problem is solved.
